/**counter**/
export const ARCHIVEFLAG = 'ARCHIVEFLAG';
export const POPCHANGEFLAG = 'POPCHANGEFLAG';
export const ADDIOBINCACHE = 'ADDIOBINCACHE';   //增加任务到缓存
export const ADDJOBARTERIDINCACHE = 'ADDJOBARTERIDINCACHE';   //隐形更新id
export const SHOWORHIDEERROR = 'SHOWORHIDEERROR';   //更新错误信息
export const ARLTERTILTLEINCAHCE = 'ARLTERTILTLEINCAHCE';   //隐形更新标题
export const ALRTERSTATUINCAHCE = 'ALRTERSTATUINCAHCE';   //隐形更新状态
export const ARLTERCONTENTINCAHCE = 'ARLTERCONTENTINCAHCE';   //隐形更新内容
export const ALTERPRIORITINCACHE = 'ALTERPRIORITINCACHE';   //隐形修改优先级


